language: ruby
rvm:
  - 2.2
before_script:
  - rake install
script:
  - awesome_bot
  - awesome_bot bin/assets/test-no-issues
  - awesome_bot bin/assets/test-no-links
  - awesome_bot bin/assets/test-parse --white-list coveralls,travis-ci
  - awesome_bot bin/assets/test-dupe --allow-dupe
  - awesome_bot bin/assets/test-timeout --allow-timeout --set-timeout 1
  - awesome_bot bin/assets/test-timeout-and-redirect --allow-timeout --set-timeout 1 --allow-redirect
  - awesome_bot bin/assets/test-redirect --allow-redirect
  - awesome_bot bin/assets/test-redirect --allow-redirect -a 301
  - awesome_bot bin/assets/test-statuses --white-list bot,bad,super
  - awesome_bot bin/assets/test-errors --allow-redirect
  - awesome_bot -f bin/assets/test-no-issues,bin/assets/test-no-links
  - awesome_bot -f bin/assets/test-no-issues,bin/assets/test-redirect --allow-redirect
  - awesome_bot bin/assets/test-no-* --allow-redirect
  - awesome_bot bin/assets/test-ssl --allow-ssl
  - awesome_bot bin/assets/test-invalid.md --allow-redirect --allow-dupe
  - awesome_bot bin/assets/test-encode.md --allow-redirect --allow-ssl --white-list sourcegraph
  - awesome_bot README.md --allow-dupe --white-list gph.is,giphy,travis-ci.org,codeload,badge,rubydoc,rubygems,circleci
  - gem install awesome_bot
